<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Contracts\Menu\Responses\" />
    <Folder Include="Contracts\Orders\Responses\" />
    <Folder Include="Contracts\Webhooks\" />
    <Folder Include="Validation\" />
  </ItemGroup>

</Project>
